### PR TITLE
Ox-based implementation of EasyRacer scenarios

### PR DESCRIPTION
**Pull request by adamw**
Not sure if you are accepting pull requests, but prompted by https://twitter.com/diesalbla/status/1621646330350243842 I've taken a shot at implementing EasyRacer using [ox](https://github.com/softwaremill/ox), which was interesting in itself to see how the API compares to other possibilities. No worries of course if you'd prefer not to merge code based on a prototype library ;)

One problem I did encounter is that scenario 3 works if the number of connection is 100 or so, but above that I'm getting `ConnectionException`s with `Connection reset by peer` messages. It might be that there are some limits on my local machine (though it should be more consistent in failing, then), or that the server has some intermittent problems.

### CODE REVIEW

**Comment by jamesward** [comment]
Thanks Adam! This is awesome!  Yes, definitely taking PRs for other implementations.  Really cool seeing the ox stuff :)

I'd be interesting to dive further into Scenario 3 to see where the problem lies.  I'll get CI setup for this and maybe that will help us narrow things down.

**Comment by jamesward** [comment]
I was able to get CI setup: https://github.com/jamesward/easyracer/actions/workflows/scala-ox.yaml

Enabled scenario3 to see what happens.

**Comment by jamesward** [comment]
Works in CI :)

**Comment by adamw** [comment]
Indeed :) thanks! must be sth local then. One day I'll investigate, though it's a regular mac, nothing out of the ordinary ;)

**Pull request merged**
